# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6e86932cde63c84e9f50313f49be0c2b8ee2ef6cd526647131a37efca10bd2dd5dce980693b4c9def59f667313405e22adb154e326d83b01cd460cde47dd513f

test:
  secret_key_base: e5ca5ee1c2e8eabd1f7c991bb83028eb38a8218b6afafa9b92721dcf4bcc8e06166e5d631cd23230f219a197a7e39af853ecd3345a3a42b3f141e709403559c9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
